language: go

# only golang>=1.2 are supported
# TODO: support building/testing with both golang and gccgo?
go:
  - 1.3

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-lxc/daily
  - sudo apt-get update

install:
  - sudo apt-get install lxc lxc-dev
  - go get code.google.com/p/go.tools/cmd/vet
  - mkdir -p $GOPATH/github.com/lxc
  - go get -v -d ./...
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/lxc/lxd/

script: "make check"
